name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: olafurpg/setup-scala@v13
        with:
          scala-version: "2.13.8"
          java-version: "adopt@1.8"
      - name: Run tests
        run: sbt ++${{ matrix.scala-version }} clean test
